INSERT INTO TODO(id,IS_DONE,TARGET_DATE,DESCRIPTION,USERNAME)
VALUES(10001,FALSE,DATE'2025-10-01','Learn Spring Boot','test');

INSERT INTO TODO(id,IS_DONE,TARGET_DATE,DESCRIPTION,USERNAME)
VALUES(10002,TRUE,CURRENT_DATE,'Fullstack Course','test');

INSERT INTO TODO(id,IS_DONE,TARGET_DATE,DESCRIPTION,USERNAME)
VALUES(10003,TRUE,CURRENT_DATE,'JPA Course','test');

INSERT INTO TODO(id,IS_DONE,TARGET_DATE,DESCRIPTION,USERNAME)
VALUES(10004,TRUE,CURRENT_DATE,'Testing Course','user');
